import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const AddressApi = createApi({
  reducerPath: "AddressApi",
  baseQuery: fetchBaseQuery({
    baseUrl: import.meta.env.VITE_API_URL,
    prepareHeaders: (headers) => {
      // Retrieve the token from sessionStorage for authenticated requests
      const token = sessionStorage.getItem("token");
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    // 1. Fetches unique cities for the Ebook purchase dropdown
    getUniqueCities: builder.query({
      query: () => "/address/fetch-all-cities",
      // Extract the data array directly for easier mapping in the Select component
      transformResponse: (response) => response.data,
    }),

    // 2. NEW: Fetches specific addresses for the logged-in user
    // This is used for the dynamic left-side profile card in the Ebooks page
    getAddressById: builder.query({
      query: (id) => `/address/fetch-address-by-id/${id}`,
      // Ensure we provide the array of addresses directly
      transformResponse: (response) => response,
    }),

    // 3. Fetches competitors based on combined user and purchased cities
    getCompetitorProducts: builder.query({
      query: ({ page = 1, limit = 10, city }) => ({
        url: '/address/fetch-seller-location-competitor',
        params: { page, limit, ...(city && { city }) },
      }),
      transformResponse: (response) => ({
        competitors: response.competitors,
        hasMore: response.hasMore,
      }),
    }),

    // 4. Fetches all countries grouped (used in landing/admin pages)
    getCountries: builder.query({
      query: () => '/address/fetch-all-country',
      transformResponse: (response) => response.data,
    }),

    // 5. Fetches all cities grouped
    getCities: builder.query({
      query: () => '/address/fetch-all-city',
      transformResponse: (response) => response.data,
      refetchOnFocus: false,
      refetchOnMountOrArgChange: false,
      keepUnusedDataFor: 3600, // Cache for 1 hour
    }),

    // 6. Fetches specific data (products/sellers) for a selected country
    getCountryData: builder.query({
      query: (country) => `/address/fetch-country-data/${country}`,
      transformResponse: (response) => response,
    }),

    // 7. Fetches suppliers/merchants specifically by region/city
    getSuppliersByCity: builder.query({
      query: (city) => `/address/find-suppliers-by-region/${city}`,
    }),

  }),
});

// Export all hooks generated by the API
export const {
  useGetUniqueCitiesQuery,
  useGetCompetitorProductsQuery,
  useGetSuppliersByCityQuery,
  useGetCountriesQuery,
  useGetCitiesQuery,
  useGetCountryDataQuery,
  useGetAddressByIdQuery // New hook for dynamic user profile cards
} = AddressApi;
